version: "3.8"

services:
  # Production Service
  sw-starter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - INIT_CRON=true
      - SEARCH_API_URL=https://swapi.py4e.com/api
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development Service
  sw-starter-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - INIT_CRON=true
      - SEARCH_API_URL=https://swapi.py4e.com/api
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    stdin_open: true
    tty: true
