FROM node:20-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm ci

COPY . .

EXPOSE 3000

ENV NODE_ENV=development
ENV INIT_CRON=true
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_SEARCH_API_URL=https://swapi.py4e.com/api

CMD ["npm", "run", "dev"]
